### ISSUE TITLE
Missing "Choices" column in the dataset?

### ISSUE THREAD

**Issue by nishkalavallabhi** [AI4Bharat/MILU#2]
Is the dataset missing a "Choices" Column in the huggingface version? There are a few questions in the form : "Choose from the below.. " and there is nothing below. For example, the first example of the Telugu subset (also the first one for Hindi) has the something like: "Put the jumbled sentences in the right order" in the Question column. There are four answer option columns with four options. There is a correct answer column. But there is no where to see what exactly are those four sentences.  See the screenshot below:

<img width="1505" alt="Image" src="https://github.com/user-attachments/assets/4e666905-cc79-4356-b240-2a007860ceb8" />

**Comment by Sshubam** [comment]
Thank you for highlighting this issue with a question in the Telugu and Hindi validation set. We have fixed this.

**Comment by nishkalavallabhi** [comment]
Hello Shubham, Thanks for the updated datasets. I think this issue still persists. There are a few other examples of this kind. For example, see the Screenshot below for Hindi (the same examples for Telugu have the same issue). For the question "निम्नलिखित शब्दों को तार्किक और अर्थपूर्ण क्रम में व्यवस्थित करने के लिए सही विकल्प चुनें।", no options are given in the question field. Three or four examples later, there is another one "निम्नलिखित विकासों का कालानुक्रमिक क्रम क्या है? " - where we have the same issue. 

<img width="1494" alt="Image" src="https://github.com/user-attachments/assets/d4853496-90e5-4ef2-9826-49ed807e6250" /> 

There are also other issues. For example, in the Telugu sample below, the fill in the blank answer is already in the text, and the blank comes at the wrong location.

<img width="1494" alt="Image" src="https://github.com/user-attachments/assets/b67b0ab7-e2dd-4fe6-bb79-168f28696c98" />
